# Generated by Django 4.2.7 on 2023-11-11 09:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 11, 9, 53, 35, 364633, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
