# Generated by Django 4.2.7 on 2023-11-11 12:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0003_alter_event_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="date",
            field=models.DateTimeField(
                default=datetime.datetime(
                    2023, 11, 11, 12, 14, 44, 387499, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
