# Generated by Django 4.2.7 on 2023-11-12 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_logo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Logo',
        ),
    ]
