# Generated by Django 4.2.7 on 2023-11-12 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_delete_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='link',
            field=models.URLField(default='http://127.0.0.1:8000/'),
        ),
    ]
